group = 'com.github.wanliyunyan'

apply plugin: 'com.android.library'

android {
    namespace = "com.wanliyunyan.proxy_aar"
    compileSdk = 33

    defaultConfig {
        minSdk = 21
        targetSdk = 33
    }

    lintOptions {
        abortOnError false
    }

    sourceSets {
        main {
            java.srcDirs = []
            manifest.srcFile 'src/main/AndroidManifest.xml'
        }
    }
}

repositories {
    google()
    mavenCentral()
    flatDir {
        dirs 'libs'  // 告诉 Gradle 从 libs/ 目录加载 .aar
    }
}

dependencies {
    implementation(name: 'proxy', ext: 'aar')
}